name: RevolutionNetworkNode
options:
  bundleIdPrefix: com.revolutionnetwork
  deploymentTarget:
    iOS: "16.0"
settings:
  PRODUCT_BUNDLE_IDENTIFIER: com.revolutionnetwork.node
  SWIFT_VERSION: "5.0"
  SWIFT_OBJC_BRIDGING_HEADER: RevolutionNetworkNode/RevolutionNetworkNode-Bridging-Header.h
targets:
  RevolutionNetworkNode:
    type: application
    platform: iOS
    sources:
      - RevolutionNetworkNode
    info:
      path: RevolutionNetworkNode/Info.plist
    settings:
      SWIFT_OBJC_BRIDGING_HEADER: RevolutionNetworkNode/RevolutionNetworkNode-Bridging-Header.h
